# Generated by Django 5.2.7 on 2025-11-15 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('ipfs', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('retailer', models.OneToOneField(db_column='retailer_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('location', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'retailer',
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('transporter', models.OneToOneField(db_column='transporter_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transporter',
            },
        ),
    ]
