# Generated by Django 5.2.7 on 2025-11-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='retailer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='transporter',
            options={'managed': False},
        ),
    ]
