import "./globals.css";

export const metadata = {
  title: "Chain tracker",
  description: "Generated by Next.js",
  icons: {
    icon: "/tracking_logo2.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
